
import React from 'react';
import { useNavigate } from 'react-router-dom';
import PageContainer from '../components/PageContainer.tsx';
import { FileText } from 'lucide-react';

const TermsScreen: React.FC = () => {
  const navigate = useNavigate();

  return (
    <PageContainer 
      title="Terms of Service" 
      showBackButton 
      onBack={() => navigate('/settings')}
    >
      <div className="p-2 text-left">
        <div className="flex flex-col items-center text-center mb-6">
          <FileText size={48} className="app-text-primary mb-3" />
          <h2 className="text-2xl font-semibold app-text-secondary">AutoInspect Terms of Service</h2>
        </div>

        <p className="text-sm text-gray-700 mb-4">
          By using AutoInspect (the "Application"), you agree to the following terms and conditions. Please read them carefully.
        </p>

        <div className="space-y-4 text-sm text-gray-600">
          <div>
            <h3 className="font-semibold text-md app-text-secondary mb-1">1. Use of the Application</h3>
            <p>AutoInspect is designed to facilitate and document vehicle inspections. You are responsible for the truthfulness and accuracy of the information you record in the Application. All information entered is stored locally on your device.</p>
          </div>

          <div>
            <h3 className="font-semibold text-md app-text-secondary mb-1">2. Intellectual Property</h3>
            <p>All content, design, source code, and other components of the Application are the property of its developers and are protected by applicable copyright and intellectual property laws. Reproduction, distribution, or modification of the Application or its content without express authorization is not permitted.</p>
          </div>

          <div>
            <h3 className="font-semibold text-md app-text-secondary mb-1">3. Limitation of Liability</h3>
            <p>The Application is provided "as is," without warranties of any kind. The developers are not liable for direct, indirect, incidental, or consequential damages, nor for losses (including data loss) arising from the use or inability to use the Application, or from the information generated by it. It is your responsibility to back up the data generated by the application.</p>
          </div>

          <div>
            <h3 className="font-semibold text-md app-text-secondary mb-1">4. Modifications to Terms</h3>
            <p>We reserve the right to update or modify these Terms of Service at any time without prior notice. Continued use of the Application after any changes implies your acceptance of the new terms. We recommend reviewing this section periodically.</p>
          </div>

          <div>
            <h3 className="font-semibold text-md app-text-secondary mb-1">5. Data Privacy</h3>
            <p>The Application stores all inspection data locally on your device. For more details on how your information is handled, please consult our Privacy Policy.</p>
          </div>
        </div>

        <p className="text-sm text-gray-600 mt-6">
          For any questions or clarifications regarding these terms, please contact us at <a href="mailto:support@autoinspect.app" className="app-text-primary hover:underline">support@autoinspect.app</a>.
        </p>
      </div>
    </PageContainer>
  );
};

export default TermsScreen;